### ISSUE TITLE
compatibility to SUPEE-6788 / Magento 1.9.2.2

### ISSUE THREAD

**Issue by hpvd** [Flagbit/Magento-ChangeAttributeSet#11]
seems to be not compatible to to SUPEE-6788 / Magento 1.9.2.2
taken from this list:
https://docs.google.com/spreadsheets/d/1LHJL6D6xm3vD349DJsDF88FBI_6PZvx_u3FioC_1-rg/

**Comment by davidfuhr** [comment]
Thanks @hpvd! We'll look into it!

**Comment by thakilla** [comment]
Hey @hpvd,
I tested the module on 1.9.2.2. There is no compatibility issue.
If you have problems running it on 1.9.2.2 let me know.

**Comment by hpvd** [comment]
thanks very much.
