### ISSUE TITLE
Visibility is set to "Catalog, Search"

### ISSUE THREAD

**Issue by sreichel** [Flagbit/Magento-ChangeAttributeSet#18]
When changing attribute sets for "induvidually not visible" products, visibility is set to "catalog, search".

ATM i have no fresh magento installation, maybe someone else can try to reproduce it.

**Comment by sreichel** [comment]
It seems, it's a magento feature. When saving a collection default values are set if not present in selection.
```
/app/code/core/Mage/Eav/Model/Entity/Attribute/Backend/Abstract.php
public function beforeSave($object)
{
    $attrCode = $this->getAttribute()->getAttributeCode();
    if (!$object->hasData($attrCode) && $this->getDefaultValue()) {
        $object->setData($attrCode, $this->getDefaultValue());
    }
}
```
So we should add all attributes with default values to addAttributeToSelect().

**Comment by madlou** [comment]
Hi @sreichel 

Many thanks for your patch.  However, to get it working correctly I had to change the below entity_type_id from 10 to 4.  I'm not familiar enough with Magento's inner workings to know why this is different for us, or how to make a generic fix

File
'app/code/community/Flagbit/ChangeAttributeSet/controllers/Adminhtml/Catalog/ProductController.php'

Line From
`->addFieldToFilter('entity_type_id', 10)`

Line To
`->addFieldToFilter('entity_type_id', 4)`

**Comment by sreichel** [comment]
Thanks @madlou!

**Comment by sreichel** [comment]
@davidfuhr can you please include this fix?

**Comment by bjoern-flagbit** [comment]
Hey, can you just create a pullrequest for that fix? Thx.
