### ISSUE TITLE
New tag with current release

### ISSUE THREAD

**Issue by jhoelzl** [Flagbit/Magento-ChangeAttributeSet#21]
Hello, since https://github.com/Flagbit/Magento-ChangeAttributeSet/releases/tag/2.1.2 there are 4 new commits, please make a new release tag including these changes. Thanks!

**Comment by bjoern-flagbit** [comment]
Done -> https://github.com/Flagbit/Magento-ChangeAttributeSet/releases/tag/2.1.3
