### ISSUE TITLE
PHP Fatal Error

### ISSUE THREAD

**Issue by arjunsol** [Flagbit/Magento-ChangeAttributeSet#22]
Call to a member function getAttributeCode() on a non-object in 
/app/code/core/Mage/Catalog/Model/Product/Type/Configurable.php on line 421, 
referer: index.php/admin/catalog_product/index/key/d881c9db7b653d90d39883d9eea0a3c0/

Only occurs when changing configurable product. Magento version 1.9.3.1

**Comment by bjoern-flagbit** [comment]
For this error we need more informations. For example did you test on a clean/new setup?
Pls re-open when this issue is still alive.

**Comment by chiragrajput** [comment]
Its showing "Fatal error: Call to a member function getAttributeCode() on a non-object in app/code/core/Mage/Catalog/Model/Product/Type/Configurable.php on line 421"

**Comment by robocrax** [comment]
Hi arjunsol,

Did you manage to find a solution for this? I'm currently facing the exact same issue on the exact same file and line 421 on configurable products only. I'll be migrating to Magento 2 and I know it's easy to change attributes there but I just want to clean the database before I migrate.

Haven't tried on a clean installation. Please let me know if there's a solution
