### ISSUE TITLE
Magento Admin   404 Error  Page not found.

### ISSUE THREAD

**Issue by sync2013** [Flagbit/Magento-ChangeAttributeSet#25]
hi,
even given full right (777) it gives following error by klicking: change attribute
"Magento Admin 404 Error Page not found."
Cache clean, flush und reindex doesnt help.
it is tested with new Installed Magento under
Magento CE 2.1.7
Debian 8.9
PHP 7.0.21
Apache 2.4

**Comment by sreichel** [comment]
Hi, this extension is for Magento 1.

**Comment by sync2013** [comment]
hi,
yes,you are  right, i want to write for this extension,
https://github.com/nicojust/magento2-change-attribute-set
i have mixed, since this one also use in composer "Flagbit\\Cas\\": 
anyway, thank you very much for your response
kind regards
