### ISSUE TITLE
Update Magento Marketplace

### ISSUE THREAD

**Issue by Geex-Renzo** [Flagbit/Magento-ChangeAttributeSet#26]
The link to `magentocommerce` doesn't work anymore, everything is redirected to `marketplace.magento.com`.

Is it going to be downloadable from there as well?

**Comment by bjoern-flagbit** [comment]
We will do this in the near future.

**Comment by bjoern-flagbit** [comment]
It takes me a lot of time but now we are done 👍 
https://marketplace.magento.com/flagbit-magento-changeattributeset.html
