### ISSUE TITLE
How to update Via CSV

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [Flagbit/Magento-ChangeAttributeSet#27]
I have so many numbers of products needs to change attribute set, is possible can I import via CSV. Let me know how to do it.

Thank You.

**Comment by bjoern-flagbit** [comment]
Hey, normally you should filter the products in the backend and then use the mass-action to update your products. I think a csv upload or script is not needed. Do you know this? Greetings.

**Comment by Jeeva-Rathinam** [comment]
Yes, you are right, but I have 1000's of SKU's in different attributes so how can i check each one. Bulk import is convenient for me. Is any possible to change via Database using sql query.

**Comment by bjoern-flagbit** [comment]
How can you check each one with an sql query? ;-)

If you want to do this i would write a script that read your csv file and change from one to another attribute set. You can use the same code we use to execute the mass-action in the backend.

**Comment by Jeeva-Rathinam** [comment]
Can I get the script  for that?

**Comment by Jeeva-Rathinam** [comment]
I found the way, **UPDATE `catalog_product_entity` SET `attribute_set_id` = '9' WHERE `catalog_product_entity`.`entity_id` = 15;**  Thanks for your responce

**Comment by bjoern-flagbit** [comment]
Nice 👍
