### ISSUE TITLE
BUG: change set deletes group prices

### ISSUE THREAD

**Issue by sreichel** [flagbit/Magento-ChangeAttributeSet#29]
When changing attributesets products group prices (untested, but guess tier prices too) will be removed.

Problem seems the `$collections->save()` call.

Quick loadheavy (?) fix could be adding `$product->getGroupPrice();` inside the loop. (same for tier prices)

https://github.com/flagbit/Magento-ChangeAttributeSet/blob/863db473410b5842d6613893e691b99090f4d147/src/app/code/community/Flagbit/ChangeAttributeSet/controllers/Adminhtml/Catalog/ProductController.php#L58-L63

**Comment by sreichel** [comment]
Update:

Instead of loading group/tier prices it also works to just call `$product->setGroupPrice(true);` 

Any ideas/comments?

**Comment by bjoern-flagbit** [comment]
@sreichel thx for you PR! Looks great.
Merged to master :-)
