### ISSUE TITLE
bulk change triggers sql state error

### ISSUE THREAD

**Issue by Chris25602** [Flagbit/Magento-ChangeAttributeSet#4]
Any time I try to process more than 50 records at a time I receive this message
<em>SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '115792-0-2' for key 'PRIMARY'</em>

Still a very useful extension just thought I would report this.

**Comment by robbieaverill** [comment]
@Chris25602 do you have indexers set to run on save for products? A full stack trace would be handy.

**Comment by bjoern-flagbit** [comment]
pls re-open when this issue is still alive
