### ISSUE TITLE
Access denied on group permissions.

### ISSUE THREAD

**Issue by rehoehle** [Flagbit/Magento-ChangeAttributeSet#5]
Hello,

there is a problem regarding the security of Magento. We use Magento 1.9.2 and the module is only working with Admin permissions. If you go to the group permissions you can mark ALL of them and its not working (Access denied when you try to save) but if you set the permissions to "all" on top then you can change the set without problems. 

Is there a solution for that problem without giving that people full access?

**Comment by rehoehle** [comment]
Is here any solution for that problem? Its a cool extension and we need them and i would be great if that small bug would be fixed.

**Comment by jhoelzl** [comment]
MIght be related: http://magento.stackexchange.com/questions/73646/access-denied-errors-after-installing-supee-6285

**Comment by nahall** [comment]
This is because of SUPEE-6285, I fixed it for my site by editing ProductController.php as you can see in my fork.

**Comment by rehoehle** [comment]
Thx that solved the problem but it would be cool if they merge that into the repository.
